name: build

on:
  push:

env: 
  TEMPLATE: '{ \"template\": \"youiservice\",\"params\" : [{ \"name\": \"includeWorker\",\"value\": \"def\"},{\"name\": \"landingZone\",\"value\": \"abc\"}]}'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{env.TEMPLATE}} | jq --arg uuid "95057cd0-db9c-11ee-a835-2d2328ea369f" '. + {guid: $uuid}'
          echo "TEMPLATE=$TEMPLATE"
